---
- block:
    - assert: 
        that: "{{ helper.networkifacename is defined }}"
    - set_fact: 
        networkifacename: "{{ helper.networkifacename }}"
  rescue:
    - set_fact:
        networkifacename: "{{ ansible_default_ipv4.interface }}"

- block:
  - set_fact:
      critical_services:
        - named
        - haproxy

- block:
  - set_fact:
      critical_services: "{{ critical_services }} + [ 'dhcpd' ]"
  when: not staticips

- block:
  - set_fact:
      critical_services: "{{ critical_services }} + [ 'keepalived' ]"
  when: high_availability is defined

- block:
  - set_fact:
      critical_services: "{{ critical_services }} + [ 'httpd' ]"
  when: helper_packages.httpd

- block:
  - set_fact:
      registry:
        - podman
        - httpd-tools
        - jq

  - set_fact:
      registry_services:
        - named
        - firewalld
        - local-registry

  - set_fact:
      registry_host: "registry.{{ dns.clusterid }}.{{ dns.domain | lower  }}"
      local_registry: "registry.{{ dns.clusterid }}.{{ dns.domain | lower  }}:5000"
#      release_image: "quay.io/{{ setup_registry.product_repo }}/{{ setup_registry.release_name }}:{{ setup_registry.release_tag }}"
  when: setup_registry is defined

- block:
  - set_fact:
      packages:
        - bind
        - bind-utils
        - firewalld
        - haproxy
        - vim
        - bash-completion
        - libselinux-python

#  - set_fact:
#      uefipkgs:
#        - shim-x64
#        - grub2-efi-x64
  
  - set_fact:
      owner: nfsnobody
      group: nfsnobody
  
  - set_fact:
      services:
        - named
        - haproxy
  when: ansible_distribution_major_version == "7"

- block:
  - set_fact:
      packages:
        - bind
        - bind-utils
        - firewalld
        - haproxy
        - vim
        - bash-completion
        - python3-libselinux
        - python3-libsemanage
  
#  - set_fact:
#      uefipkgs:
#        - shim-x64
#        - grub2-efi-x64
#

  # See Fedora Wiki for changes:
  # https://fedoraproject.org/wiki/Changes/RenameNobodyUser
  - set_fact:
      owner: nobody
      group: nobody
  
  - set_fact:
      services:
        - named
        - haproxy
  when: ansible_distribution_major_version == "8"

- block:
  - set_fact:
      packages: "{{ packages }} + [ 'httpd' ]"
      services: "{{ services }} + [ 'httpd' ]"
  when: helper_packages.httpd

- block:
  - set_fact:
      packages: "{{ packages }} + [ 'nfs-utils' ]"
      services: "{{ services }} + [ 'nfs-server', 'rpcbind' ]"
  when: helper_packages.nfsd

- block:
  - set_fact:
      packages: "{{ packages }} + [ 'dhcp-server' ]"
      # packages: "{{ packages }} + [ 'dhcpd', 'tftp-server' ]"
  when: not staticips

- block:
  - set_fact:
      packages: "{{ packages }} + [ 'syslinux' ]"
  when: not staticips and not ppc64le

- block:
  - set_fact:
      packages: "{{ packages }} + [ 'rsync' ]"
  when: high_availability is defined

- block:
  - set_fact:
      packages: "{{ packages }} + [ 'podman' ]"
  when: helper_packages.podman
