---
# tasks file for setup-keepalived

- name: Install keepalived packages
  package:
    name: keepalived
    state: present

- name: Generate a random external password for Keepalived’s AUTH_PASS
  shell: uuidgen
  register: password
  run_once: true

- name: Set high_priority fact
  set_fact:
    high_priority: "{{ item.priority }}"
  with_items:
    - "{{ high_availability.helpernodes }}"
  when: item.state == "MASTER"

- name: Set low_priority fact
  set_fact:
    low_priority: "{{ low_priority | default([]) }} + [ {{ item.priority }} ]"
  with_items:
    - "{{ high_availability.helpernodes }}"
  when: item.state == "BACKUP"

- name: Set calibrated_priority fact
  set_fact:
    calibrated_priority: "{{ high_priority|int - low_priority|min + 10 }}"

- name: Generate keepalived configuration file
  template:
    src: ../templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
    
- name: Copy vrrp_script.sh file
  copy:
    src: ../files/vrrp_script.sh
    dest: /etc/keepalived/vrrp_script.sh

- firewalld:
    rich_rule: rule protocol value="vrrp" accept
    permanent: yes
    state: enabled

- firewalld:
    rich_rule: rule protocol value="vrrp" accept
    permanent: yes
    zone: external
    state: enabled

  when: high_availability_ext.networkifacename is defined and high_availability_ext.ipaddr is defined
    
- name: Reload service firewalld
  service:
    name: firewalld
    state: reloaded

- name: Enable and start service keepalived
  service:
    name: keepalived
    enabled: yes
    state: restarted

